[package]
name = "wechat_store"
version = "0.2.0"
authors = ["shaipe <shaipe@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
